name: Streamlit Keep Alive

on:
  schedule:
    # 每天北京时间上午 9 点（UTC 1:00）自动运行
    - cron: '0 1 * * *'
  workflow_dispatch: # 允许手动点击按钮测试

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Visit Streamlit App
        run: |
          curl -I "https://share.streamlit.io/app/ai-renovation-pro-wjrpubpumdnjv6rorc3b6w/"
